server:
  port: 8087

spring:

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  sql:
    init:
      mode: always

  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    openai:
      api-key: ${OPENAI_API_KEY}
jwt:
  secret: ${JWT_SECRET}
